# Generated by Django 5.0.14 on 2026-08-12 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accreditation", "0002_alter_accreditationlevel_code_and_more"),
        ("inventory", "0001_initial"),
        ("teams", "0002_alter_branch_city_alter_branch_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="accreditationrequirement",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="requirements",
                to="inventory.equipmentcategory",
                verbose_name="Ekipman Kategorisi",
            ),
        ),
        migrations.AlterField(
            model_name="accreditationrequirement",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requirements",
                to="accreditation.accreditationlevel",
                verbose_name="Akreditasyon Seviyesi",
            ),
        ),
        migrations.AlterField(
            model_name="accreditationrequirement",
            name="min_quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Asgari Miktar"),
        ),
        migrations.AlterField(
            model_name="custodyassignment",
            name="assigned_at",
            field=models.DateTimeField(verbose_name="Teslim Tarihi"),
        ),
        migrations.AlterField(
            model_name="custodyassignment",
            name="assigned_to_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custody_assignments",
                to="teams.team",
                verbose_name="Zimmetli Ekip",
            ),
        ),
        migrations.AlterField(
            model_name="custodyassignment",
            name="assigned_to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="custody_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Zimmetli Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="custodyassignment",
            name="condition_notes",
            field=models.TextField(blank=True, verbose_name="Durum Notları"),
        ),
        migrations.AlterField(
            model_name="custodyassignment",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="custody_history",
                to="inventory.inventoryitem",
                verbose_name="Envanter Kalemi",
            ),
        ),
        migrations.AlterField(
            model_name="custodyassignment",
            name="returned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="İade Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="equipmentcategory",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Kategori Adı"),
        ),
        migrations.AlterField(
            model_name="equipmentcategory",
            name="unit",
            field=models.CharField(default="adet", max_length=30, verbose_name="Birim"),
        ),
        migrations.AlterField(
            model_name="historicalcustodyassignment",
            name="assigned_at",
            field=models.DateTimeField(verbose_name="Teslim Tarihi"),
        ),
        migrations.AlterField(
            model_name="historicalcustodyassignment",
            name="assigned_to_team",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="teams.team",
                verbose_name="Zimmetli Ekip",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustodyassignment",
            name="assigned_to_user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Zimmetli Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustodyassignment",
            name="condition_notes",
            field=models.TextField(blank=True, verbose_name="Durum Notları"),
        ),
        migrations.AlterField(
            model_name="historicalcustodyassignment",
            name="item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="inventory.inventoryitem",
                verbose_name="Envanter Kalemi",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcustodyassignment",
            name="returned_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="İade Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="inventory.equipmentcategory",
                verbose_name="Kategori",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="expires_at",
            field=models.DateField(
                blank=True,
                help_text="Son kullanma tarihi olan malzemeler için (ip, medikal vb.).",
                null=True,
                verbose_name="Son Kullanma Tarihi",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="owner_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_items",
                to="teams.team",
                verbose_name="Sahip Ekip",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="serial_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Seri Numarası"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Aktif"),
                    ("maintenance", "Bakımda"),
                    ("retired", "Hizmet Dışı"),
                    ("lost", "Kayıp"),
                ],
                default="active",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
    ]
