# Generated by Django 5.0.14 on 2026-08-12 19:49
# El ile düzenlendi: mevcut kayıtlara çakışmasız kod atamak için 3 adıma bölündü
# (önce unique'siz ekle, doldur, sonra unique constraint ekle).

from django.db import migrations, models


def backfill_codes(apps, schema_editor):
    InventoryItem = apps.get_model("inventory", "InventoryItem")
    for i, item in enumerate(InventoryItem.objects.filter(code="").order_by("id"), start=1):
        item.code = f"ENV-{i:05d}"
        item.save(update_fields=["code"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_accreditationrequirement_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Boş bırakılırsa sistem otomatik üretir (ör. ENV-00001). İstersen elle değiştirebilirsin.",
                max_length=20,
                verbose_name="Envanter Kodu",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_codes, noop),
        migrations.AlterField(
            model_name="inventoryitem",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Boş bırakılırsa sistem otomatik üretir (ör. ENV-00001). İstersen elle değiştirebilirsin.",
                max_length=20,
                unique=True,
                verbose_name="Envanter Kodu",
            ),
        ),
    ]
