# Generated by Django 5.0.14 on 2026-08-12 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0003_alter_team_unique_together_team_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Grup Adı")),
                (
                    "include_all_users",
                    models.BooleanField(
                        default=False,
                        help_text="İşaretlenirse ekip/rol filtresi yok sayılır, telefon numarası olan tüm kullanıcılar hedeflenir.",
                        verbose_name="Tüm Kullanıcılar",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "roles",
                    models.ManyToManyField(
                        blank=True,
                        related_name="notification_segments",
                        to="teams.role",
                        verbose_name="Roller",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        blank=True,
                        related_name="notification_segments",
                        to="teams.team",
                        verbose_name="Ekipler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim Grubu",
                "verbose_name_plural": "Bildirim Grupları",
            },
        ),
        migrations.CreateModel(
            name="SmsCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="459 karakteri aşan mesajlar birden fazla SMS olarak ücretlendirilebilir.",
                        verbose_name="Mesaj Metni",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Taslak"),
                            ("sent", "Gönderildi"),
                            ("failed", "Başarısız"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Durum",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Gönderim Tarihi"
                    ),
                ),
                (
                    "recipient_count",
                    models.PositiveIntegerField(default=0, verbose_name="Alıcı Sayısı"),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Sağlayıcı Yanıtı"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "segment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="campaigns",
                        to="notifications.notificationsegment",
                        verbose_name="Hedef Grup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Toplu SMS Gönderimi",
                "verbose_name_plural": "Toplu SMS Gönderimleri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SmsRecipientLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Telefon Numarası"),
                ),
                (
                    "is_success",
                    models.BooleanField(default=False, verbose_name="Başarılı mı"),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Sağlayıcı Mesaj ID"
                    ),
                ),
                (
                    "error_detail",
                    models.TextField(blank=True, verbose_name="Hata Detayı"),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_logs",
                        to="notifications.smscampaign",
                        verbose_name="Gönderim",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Alıcı Kaydı",
                "verbose_name_plural": "SMS Alıcı Kayıtları",
            },
        ),
    ]
