# Generated by Django 5.0.14 on 2026-08-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("teams", "0003_alter_team_unique_together_team_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smscampaign",
            name="segment",
        ),
        migrations.AddField(
            model_name="smscampaign",
            name="include_all_users",
            field=models.BooleanField(
                default=False,
                help_text="İşaretlenirse ekip seçimi yok sayılır, telefon numarası olan tüm kullanıcılara gönderilir.",
                verbose_name="Tüm Kullanıcılar",
            ),
        ),
        migrations.AddField(
            model_name="smscampaign",
            name="teams",
            field=models.ManyToManyField(
                blank=True,
                related_name="sms_campaigns",
                to="teams.team",
                verbose_name="Hedef Ekipler",
            ),
        ),
        migrations.DeleteModel(
            name="NotificationSegment",
        ),
    ]
