# Generated by Django 5.0.14 on 2026-08-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_remove_smscampaign_segment_and_more"),
        ("teams", "0003_alter_team_unique_together_team_city_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smscampaign",
            name="include_all_users",
        ),
        migrations.AlterField(
            model_name="smscampaign",
            name="teams",
            field=models.ManyToManyField(
                related_name="sms_campaigns",
                to="teams.team",
                verbose_name="Hedef Ekipler",
            ),
        ),
    ]
