# Generated by Django 5.0.14 on 2026-08-12 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Şehir"),
        ),
        migrations.AlterField(
            model_name="branch",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Şube Adı"),
        ),
        migrations.AlterField(
            model_name="historicalteammembership",
            name="joined_at",
            field=models.DateField(verbose_name="Katılma Tarihi"),
        ),
        migrations.AlterField(
            model_name="historicalteammembership",
            name="left_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ayrılma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="historicalteammembership",
            name="team",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="teams.team",
                verbose_name="Ekip",
            ),
        ),
        migrations.AlterField(
            model_name="historicalteammembership",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserteamrole",
            name="assigned_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Atanma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserteamrole",
            name="role",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="teams.role",
                verbose_name="Rol",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserteamrole",
            name="team",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="teams.team",
                verbose_name="Ekip",
            ),
        ),
        migrations.AlterField(
            model_name="historicaluserteamrole",
            name="user",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="code",
            field=models.SlugField(unique=True, verbose_name="Kod"),
        ),
        migrations.AlterField(
            model_name="role",
            name="description",
            field=models.TextField(blank=True, verbose_name="Açıklama"),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Rol Adı"),
        ),
        migrations.AlterField(
            model_name="team",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="teams",
                to="teams.branch",
                verbose_name="Şube",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Oluşturulma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Ekip Adı"),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="joined_at",
            field=models.DateField(verbose_name="Katılma Tarihi"),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="left_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Ayrılma Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="teams.team",
                verbose_name="Ekip",
            ),
        ),
        migrations.AlterField(
            model_name="teammembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
        migrations.AlterField(
            model_name="userteamrole",
            name="assigned_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Atanma Tarihi"),
        ),
        migrations.AlterField(
            model_name="userteamrole",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignments",
                to="teams.role",
                verbose_name="Rol",
            ),
        ),
        migrations.AlterField(
            model_name="userteamrole",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_roles",
                to="teams.team",
                verbose_name="Ekip",
            ),
        ),
        migrations.AlterField(
            model_name="userteamrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
    ]
