# Generated by Django 5.0.14 on 2026-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_alter_branch_city_alter_branch_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="city",
            field=models.CharField(
                default="Bilinmiyor", max_length=100, verbose_name="Şehir"
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("city", "name")},
        ),
        migrations.RemoveField(
            model_name="team",
            name="branch",
        ),
        migrations.DeleteModel(
            name="Branch",
        ),
    ]
