# Generated by Django 5.0.14 on 2026-08-12 11:52

import apps.forms_app.fields
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=100, verbose_name="Soyad")),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Telefon"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Şehir")),
                ("birth_date", models.DateField(verbose_name="Doğum Tarihi")),
                (
                    "interested_area",
                    models.CharField(
                        choices=[
                            ("arama", "Arama"),
                            ("kurtarma", "Kurtarma"),
                            ("lojistik", "Lojistik"),
                            ("ilk_yardim", "İlk Yardım"),
                            ("k9", "K9 (Arama Köpeği)"),
                            ("diger", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="İlgilendiği Alan",
                    ),
                ),
                (
                    "motivation",
                    models.TextField(verbose_name="Neden gönüllü olmak istiyorsunuz?"),
                ),
                (
                    "health_declaration",
                    apps.forms_app.fields.EncryptedTextField(
                        help_text="Saha çalışmasına engel olabilecek bir sağlık durumunuz varsa belirtin, yoksa 'yok' yazabilirsiniz.",
                        verbose_name="Sağlık Durumu / Fiziksel Uygunluk Beyanı",
                    ),
                ),
                (
                    "kvkk_consent",
                    models.BooleanField(
                        verbose_name="KVKK Aydınlatma Metnini okudum, kişisel verilerimin işlenmesini kabul ediyorum."
                    ),
                ),
                (
                    "health_data_consent",
                    models.BooleanField(
                        verbose_name="Sağlık durumuma ilişkin özel nitelikli verimin bu başvuru kapsamında işlenmesine açıkça rıza gösteriyorum."
                    ),
                ),
                ("consent_given_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Değerlendirme Bekliyor"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Değerlendirme Notu"),
                ),
            ],
            options={
                "verbose_name": "Gönüllü Başvurusu",
                "verbose_name_plural": "Gönüllü Başvuruları",
                "ordering": ["-consent_given_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalVolunteerApplication",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=100, verbose_name="Soyad")),
                ("email", models.EmailField(max_length=254, verbose_name="E-posta")),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Telefon"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Şehir")),
                ("birth_date", models.DateField(verbose_name="Doğum Tarihi")),
                (
                    "interested_area",
                    models.CharField(
                        choices=[
                            ("arama", "Arama"),
                            ("kurtarma", "Kurtarma"),
                            ("lojistik", "Lojistik"),
                            ("ilk_yardim", "İlk Yardım"),
                            ("k9", "K9 (Arama Köpeği)"),
                            ("diger", "Diğer"),
                        ],
                        max_length=20,
                        verbose_name="İlgilendiği Alan",
                    ),
                ),
                (
                    "motivation",
                    models.TextField(verbose_name="Neden gönüllü olmak istiyorsunuz?"),
                ),
                (
                    "health_declaration",
                    apps.forms_app.fields.EncryptedTextField(
                        help_text="Saha çalışmasına engel olabilecek bir sağlık durumunuz varsa belirtin, yoksa 'yok' yazabilirsiniz.",
                        verbose_name="Sağlık Durumu / Fiziksel Uygunluk Beyanı",
                    ),
                ),
                (
                    "kvkk_consent",
                    models.BooleanField(
                        verbose_name="KVKK Aydınlatma Metnini okudum, kişisel verilerimin işlenmesini kabul ediyorum."
                    ),
                ),
                (
                    "health_data_consent",
                    models.BooleanField(
                        verbose_name="Sağlık durumuma ilişkin özel nitelikli verimin bu başvuru kapsamında işlenmesine açıkça rıza gösteriyorum."
                    ),
                ),
                ("consent_given_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Değerlendirme Bekliyor"),
                            ("approved", "Onaylandı"),
                            ("rejected", "Reddedildi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="Değerlendirme Notu"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Gönüllü Başvurusu",
                "verbose_name_plural": "historical Gönüllü Başvuruları",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SensitiveFieldAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "accessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="forms_app.volunteerapplication",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hassas Veri Erişim Kaydı",
                "verbose_name_plural": "Hassas Veri Erişim Kayıtları",
                "ordering": ["-accessed_at"],
            },
        ),
    ]
