# Generated by Django 5.0.14 on 2026-08-12 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalvolunteerapplication",
            name="consent_given_at",
            field=models.DateTimeField(
                blank=True, editable=False, verbose_name="Başvuru Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="historicalvolunteerapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Değerlendirme Bekliyor"),
                    ("approved", "Onaylandı"),
                    ("rejected", "Reddedildi"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="sensitivefieldaccesslog",
            name="accessed_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Görüntülenme Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="sensitivefieldaccesslog",
            name="accessed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Görüntüleyen",
            ),
        ),
        migrations.AlterField(
            model_name="sensitivefieldaccesslog",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="access_logs",
                to="forms_app.volunteerapplication",
                verbose_name="Başvuru",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="consent_given_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Başvuru Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="volunteerapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Değerlendirme Bekliyor"),
                    ("approved", "Onaylandı"),
                    ("rejected", "Reddedildi"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
    ]
