# Generated by Django 5.0.14 on 2026-08-12 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                (
                    "file",
                    models.FileField(
                        upload_to="knowledge_base/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                        verbose_name="PDF Dosyası",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Yayınla"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bilgi Bankası Dokümanı",
                "verbose_name_plural": "Bilgi Bankası Dokümanları",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
