# Generated by Django 5.0.14 on 2026-08-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgebasedocument",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yüklenme Tarihi"
            ),
        ),
    ]
