# Generated by Django 5.0.14 on 2026-08-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_knowledgebasedocument_uploaded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="İl"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Sıra"),
                ),
            ],
            options={
                "verbose_name": "Hava Durumu İli",
                "verbose_name_plural": "Hava Durumu İlleri",
                "ordering": ["order", "name"],
            },
        ),
    ]
