# Generated by Django 5.0.14 on 2026-08-13 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_weatherlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("body", models.TextField(verbose_name="İçerik")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Yayınla"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Yayın Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Duyuru",
                "verbose_name_plural": "Duyurular",
                "ordering": ["-published_at"],
            },
        ),
    ]
