# Generated by Django 5.0.14 on 2026-08-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="announcements/%Y/%m/", verbose_name="Görsel"
            ),
        ),
    ]
