# Generated by Django 5.0.14 on 2026-08-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_announcement_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisasterNewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="Slug"),
                ),
                (
                    "title",
                    models.CharField(max_length=300, verbose_name="Başlık (Türkçe)"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="Özet (Türkçe)")),
                (
                    "full_content",
                    models.TextField(blank=True, verbose_name="Tam İçerik (Türkçe)"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("aa", "Anadolu Ajansı"),
                            ("reliefweb", "ReliefWeb (BM OCHA)"),
                        ],
                        max_length=20,
                        verbose_name="Kaynak",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        max_length=500,
                        unique=True,
                        verbose_name="Orijinal Kaynak Linki",
                    ),
                ),
                (
                    "image",
                    models.URLField(
                        blank=True, max_length=500, verbose_name="Görsel URL"
                    ),
                ),
                ("published_at", models.DateTimeField(verbose_name="Yayın Tarihi")),
                (
                    "fetched_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Çekilme Tarihi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Afet Haberi",
                "verbose_name_plural": "Afet Haberleri",
                "ordering": ["-published_at"],
            },
        ),
    ]
