# Generated by Django 5.0.14 on 2026-08-12 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0003_alter_team_unique_together_team_city_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("description", models.TextField(blank=True, verbose_name="Açıklama")),
                ("start_at", models.DateTimeField(verbose_name="Başlangıç")),
                (
                    "end_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Bitiş"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Konum"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan",
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        related_name="events",
                        to="teams.team",
                        verbose_name="İlgili Ekipler",
                    ),
                ),
            ],
            options={
                "verbose_name": "Faaliyet",
                "verbose_name_plural": "Faaliyetler",
                "ordering": ["start_at"],
            },
        ),
    ]
