# Generated by Django 5.0.14 on 2026-08-12 19:17

import apps.forms_app.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_options_alter_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserHealthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A Rh+"),
                            ("A-", "A Rh-"),
                            ("B+", "B Rh+"),
                            ("B-", "B Rh-"),
                            ("AB+", "AB Rh+"),
                            ("AB-", "AB Rh-"),
                            ("0+", "0 Rh+"),
                            ("0-", "0 Rh-"),
                        ],
                        max_length=3,
                        verbose_name="Kan Grubu",
                    ),
                ),
                (
                    "chronic_conditions",
                    apps.forms_app.fields.EncryptedTextField(
                        blank=True,
                        help_text="Varsa kronik rahatsızlıkları belirtin.",
                        verbose_name="Kronik Hastalıklar",
                    ),
                ),
                (
                    "medications",
                    apps.forms_app.fields.EncryptedTextField(
                        blank=True, verbose_name="Sürekli Kullanılan İlaçlar"
                    ),
                ),
                (
                    "allergies",
                    apps.forms_app.fields.EncryptedTextField(
                        blank=True,
                        help_text="İlaç, gıda ya da diğer bilinen alerjiler.",
                        verbose_name="Alerjiler",
                    ),
                ),
                (
                    "fitness_notes",
                    apps.forms_app.fields.EncryptedTextField(
                        blank=True,
                        help_text="Saha görevine engel olabilecek fiziksel durum notları.",
                        verbose_name="Fiziksel Uygunluk Notları",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Acil Durum İrtibat Kişisi",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Acil Durum İrtibat Telefonu",
                    ),
                ),
                (
                    "last_medical_check_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Son Sağlık Kontrolü / Rapor Tarihi",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Güncellenme Tarihi"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sağlık Profili",
                "verbose_name_plural": "Sağlık Profilleri",
            },
        ),
        migrations.CreateModel(
            name="HealthProfileAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accessed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Görüntülenme Tarihi"
                    ),
                ),
                (
                    "accessed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Görüntüleyen",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_logs",
                        to="accounts.userhealthprofile",
                        verbose_name="Sağlık Profili",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sağlık Profili Erişim Kaydı",
                "verbose_name_plural": "Sağlık Profili Erişim Kayıtları",
                "ordering": ["-accessed_at"],
            },
        ),
    ]
