# Generated by Django 5.0.14 on 2026-08-18 12:20

import apps.forms_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adres"),
        ),
        migrations.AddField(
            model_name="user",
            name="driving_license",
            field=models.CharField(blank=True, max_length=50, verbose_name="Ehliyet"),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.CharField(blank=True, max_length=150, verbose_name="Mesleği"),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="national_id",
            field=apps.forms_app.fields.EncryptedTextField(
                blank=True,
                help_text="11 haneli T.C. Kimlik Numarası.",
                verbose_name="T.C. Kimlik No",
            ),
        ),
    ]
