# Generated by Django 5.0.14 on 2026-08-18 12:51

import apps.forms_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_address_user_driving_license_user_occupation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="passport_info",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Pasaport Bilgileri"
            ),
        ),
        migrations.AddField(
            model_name="userhealthprofile",
            name="disability_status",
            field=apps.forms_app.fields.EncryptedTextField(
                blank=True,
                help_text="Varsa engel durumu ve derecesi.",
                verbose_name="Engel Durumu",
            ),
        ),
    ]
