# Generated by Django 5.0.14 on 2026-08-12 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accreditation", "0001_initial"),
        ("teams", "0002_alter_branch_city_alter_branch_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="accreditationlevel",
            name="code",
            field=models.SlugField(unique=True, verbose_name="Kod"),
        ),
        migrations.AlterField(
            model_name="accreditationlevel",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Seviye Adı"),
        ),
        migrations.AlterField(
            model_name="accreditationlevel",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Sıra"),
        ),
        migrations.AlterField(
            model_name="accreditationrecord",
            name="certifying_body",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Denetleyen Kurum"
            ),
        ),
        migrations.AlterField(
            model_name="accreditationrecord",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="accreditation.accreditationlevel",
                verbose_name="Akreditasyon Seviyesi",
            ),
        ),
        migrations.AlterField(
            model_name="accreditationrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Aktif"),
                    ("pending", "Beklemede"),
                    ("expired", "Süresi Doldu"),
                    ("suspended", "Askıya Alındı"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="accreditationrecord",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accreditation_records",
                to="teams.team",
                verbose_name="Ekip",
            ),
        ),
        migrations.AlterField(
            model_name="accreditationrecord",
            name="valid_from",
            field=models.DateField(
                blank=True, null=True, verbose_name="Geçerlilik Başlangıcı"
            ),
        ),
        migrations.AlterField(
            model_name="accreditationrecord",
            name="valid_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="Geçerlilik Bitişi"
            ),
        ),
        migrations.AlterField(
            model_name="certification",
            name="code",
            field=models.SlugField(unique=True, verbose_name="Kod"),
        ),
        migrations.AlterField(
            model_name="certification",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Sertifika Adı"),
        ),
        migrations.AlterField(
            model_name="certification",
            name="validity_period_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Boş bırakılırsa süresiz kabul edilir.",
                null=True,
                verbose_name="Geçerlilik Süresi (gün)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccreditationrecord",
            name="certifying_body",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Denetleyen Kurum"
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccreditationrecord",
            name="level",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="accreditation.accreditationlevel",
                verbose_name="Akreditasyon Seviyesi",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccreditationrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Aktif"),
                    ("pending", "Beklemede"),
                    ("expired", "Süresi Doldu"),
                    ("suspended", "Askıya Alındı"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccreditationrecord",
            name="team",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="teams.team",
                verbose_name="Ekip",
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccreditationrecord",
            name="valid_from",
            field=models.DateField(
                blank=True, null=True, verbose_name="Geçerlilik Başlangıcı"
            ),
        ),
        migrations.AlterField(
            model_name="historicalaccreditationrecord",
            name="valid_until",
            field=models.DateField(
                blank=True, null=True, verbose_name="Geçerlilik Bitişi"
            ),
        ),
        migrations.AlterField(
            model_name="usercertification",
            name="certification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="holders",
                to="accreditation.certification",
                verbose_name="Sertifika",
            ),
        ),
        migrations.AlterField(
            model_name="usercertification",
            name="document_ref",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Belge Referansı"
            ),
        ),
        migrations.AlterField(
            model_name="usercertification",
            name="expires_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Geçerlilik Bitiş Tarihi"
            ),
        ),
        migrations.AlterField(
            model_name="usercertification",
            name="issued_at",
            field=models.DateField(verbose_name="Veriliş Tarihi"),
        ),
        migrations.AlterField(
            model_name="usercertification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="certifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Kullanıcı",
            ),
        ),
    ]
